apiVersion: v1
kind: Service

metadata:
  name: devloop-backend-service

spec:
  type: NodePort

  selector:
    app: devloop-backend

  ports:
    - port: 2008
      targetPort: 2008
      nodePort: 32008